//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCB.JPSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private int BalanceField;
        
        private bool LinkedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Linked {
            get {
                return this.LinkedField;
            }
            set {
                if ((this.LinkedField.Equals(value) != true)) {
                    this.LinkedField = value;
                    this.RaisePropertyChanged("Linked");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JPSService.JPSServiceSoap")]
    public interface JPSServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        NCB.JPSService.HelloWorldResponse HelloWorld(NCB.JPSService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.JPSService.HelloWorldResponse> HelloWorldAsync(NCB.JPSService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        NCB.JPSService.RegisterResponse Register(NCB.JPSService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.JPSService.RegisterResponse> RegisterAsync(NCB.JPSService.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        NCB.JPSService.LoginResponse Login(NCB.JPSService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.JPSService.LoginResponse> LoginAsync(NCB.JPSService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateBalance", ReplyAction="*")]
        NCB.JPSService.updateBalanceResponse updateBalance(NCB.JPSService.updateBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.JPSService.updateBalanceResponse> updateBalanceAsync(NCB.JPSService.updateBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateLinkedStatus", ReplyAction="*")]
        NCB.JPSService.updateLinkedStatusResponse updateLinkedStatus(NCB.JPSService.updateLinkedStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateLinkedStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.JPSService.updateLinkedStatusResponse> updateLinkedStatusAsync(NCB.JPSService.updateLinkedStatusRequest request);
        
        // CODEGEN: Generating message contract since element name getUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUser", ReplyAction="*")]
        NCB.JPSService.getUserResponse getUser(NCB.JPSService.getUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUser", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.JPSService.getUserResponse> getUserAsync(NCB.JPSService.getUserRequest request);
        
        // CODEGEN: Generating message contract since element name GetUsernameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsername", ReplyAction="*")]
        NCB.JPSService.GetUsernameResponse GetUsername(NCB.JPSService.GetUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.JPSService.GetUsernameResponse> GetUsernameAsync(NCB.JPSService.GetUsernameRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserId", ReplyAction="*")]
        NCB.JPSService.GetUserIdResponse GetUserId(NCB.JPSService.GetUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.JPSService.GetUserIdResponse> GetUserIdAsync(NCB.JPSService.GetUserIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserEmailResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserEmail", ReplyAction="*")]
        NCB.JPSService.GetUserEmailResponse GetUserEmail(NCB.JPSService.GetUserEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.JPSService.GetUserEmailResponse> GetUserEmailAsync(NCB.JPSService.GetUserEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserBalance", ReplyAction="*")]
        int GetUserBalance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetUserBalanceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserLinkedStatus", ReplyAction="*")]
        bool GetUserLinkedStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserLinkedStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> GetUserLinkedStatusAsync();
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserLinkedStatusById", ReplyAction="*")]
        NCB.JPSService.GetUserLinkedStatusByIdResponse GetUserLinkedStatusById(NCB.JPSService.GetUserLinkedStatusByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserLinkedStatusById", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.JPSService.GetUserLinkedStatusByIdResponse> GetUserLinkedStatusByIdAsync(NCB.JPSService.GetUserLinkedStatusByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(NCB.JPSService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(NCB.JPSService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(NCB.JPSService.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string id, string name, string email, string password) {
            this.id = id;
            this.name = name;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(NCB.JPSService.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterResponseBody {
        
        public RegisterResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(NCB.JPSService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string id, string password) {
            this.id = id;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(NCB.JPSService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateBalance", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.updateBalanceRequestBody Body;
        
        public updateBalanceRequest() {
        }
        
        public updateBalanceRequest(NCB.JPSService.updateBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int balance;
        
        public updateBalanceRequestBody() {
        }
        
        public updateBalanceRequestBody(string id, int balance) {
            this.id = id;
            this.balance = balance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.updateBalanceResponseBody Body;
        
        public updateBalanceResponse() {
        }
        
        public updateBalanceResponse(NCB.JPSService.updateBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateBalanceResponseBody {
        
        public updateBalanceResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateLinkedStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateLinkedStatus", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.updateLinkedStatusRequestBody Body;
        
        public updateLinkedStatusRequest() {
        }
        
        public updateLinkedStatusRequest(NCB.JPSService.updateLinkedStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateLinkedStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool status;
        
        public updateLinkedStatusRequestBody() {
        }
        
        public updateLinkedStatusRequestBody(string id, bool status) {
            this.id = id;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateLinkedStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateLinkedStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.updateLinkedStatusResponseBody Body;
        
        public updateLinkedStatusResponse() {
        }
        
        public updateLinkedStatusResponse(NCB.JPSService.updateLinkedStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateLinkedStatusResponseBody {
        
        public updateLinkedStatusResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUser", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.getUserRequestBody Body;
        
        public getUserRequest() {
        }
        
        public getUserRequest(NCB.JPSService.getUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUserRequestBody {
        
        public getUserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.getUserResponseBody Body;
        
        public getUserResponse() {
        }
        
        public getUserResponse(NCB.JPSService.getUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NCB.JPSService.User getUserResult;
        
        public getUserResponseBody() {
        }
        
        public getUserResponseBody(NCB.JPSService.User getUserResult) {
            this.getUserResult = getUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsername", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.GetUsernameRequestBody Body;
        
        public GetUsernameRequest() {
        }
        
        public GetUsernameRequest(NCB.JPSService.GetUsernameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsernameRequestBody {
        
        public GetUsernameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsernameResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.GetUsernameResponseBody Body;
        
        public GetUsernameResponse() {
        }
        
        public GetUsernameResponse(NCB.JPSService.GetUsernameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsernameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUsernameResult;
        
        public GetUsernameResponseBody() {
        }
        
        public GetUsernameResponseBody(string GetUsernameResult) {
            this.GetUsernameResult = GetUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserId", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.GetUserIdRequestBody Body;
        
        public GetUserIdRequest() {
        }
        
        public GetUserIdRequest(NCB.JPSService.GetUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUserIdRequestBody {
        
        public GetUserIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.GetUserIdResponseBody Body;
        
        public GetUserIdResponse() {
        }
        
        public GetUserIdResponse(NCB.JPSService.GetUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserIdResult;
        
        public GetUserIdResponseBody() {
        }
        
        public GetUserIdResponseBody(string GetUserIdResult) {
            this.GetUserIdResult = GetUserIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserEmail", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.GetUserEmailRequestBody Body;
        
        public GetUserEmailRequest() {
        }
        
        public GetUserEmailRequest(NCB.JPSService.GetUserEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUserEmailRequestBody {
        
        public GetUserEmailRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.GetUserEmailResponseBody Body;
        
        public GetUserEmailResponse() {
        }
        
        public GetUserEmailResponse(NCB.JPSService.GetUserEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserEmailResult;
        
        public GetUserEmailResponseBody() {
        }
        
        public GetUserEmailResponseBody(string GetUserEmailResult) {
            this.GetUserEmailResult = GetUserEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserLinkedStatusByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserLinkedStatusById", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.GetUserLinkedStatusByIdRequestBody Body;
        
        public GetUserLinkedStatusByIdRequest() {
        }
        
        public GetUserLinkedStatusByIdRequest(NCB.JPSService.GetUserLinkedStatusByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserLinkedStatusByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetUserLinkedStatusByIdRequestBody() {
        }
        
        public GetUserLinkedStatusByIdRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserLinkedStatusByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserLinkedStatusByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.JPSService.GetUserLinkedStatusByIdResponseBody Body;
        
        public GetUserLinkedStatusByIdResponse() {
        }
        
        public GetUserLinkedStatusByIdResponse(NCB.JPSService.GetUserLinkedStatusByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserLinkedStatusByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetUserLinkedStatusByIdResult;
        
        public GetUserLinkedStatusByIdResponseBody() {
        }
        
        public GetUserLinkedStatusByIdResponseBody(bool GetUserLinkedStatusByIdResult) {
            this.GetUserLinkedStatusByIdResult = GetUserLinkedStatusByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JPSServiceSoapChannel : NCB.JPSService.JPSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JPSServiceSoapClient : System.ServiceModel.ClientBase<NCB.JPSService.JPSServiceSoap>, NCB.JPSService.JPSServiceSoap {
        
        public JPSServiceSoapClient() {
        }
        
        public JPSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JPSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JPSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JPSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.JPSService.HelloWorldResponse NCB.JPSService.JPSServiceSoap.HelloWorld(NCB.JPSService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            NCB.JPSService.HelloWorldRequest inValue = new NCB.JPSService.HelloWorldRequest();
            inValue.Body = new NCB.JPSService.HelloWorldRequestBody();
            NCB.JPSService.HelloWorldResponse retVal = ((NCB.JPSService.JPSServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.JPSService.HelloWorldResponse> NCB.JPSService.JPSServiceSoap.HelloWorldAsync(NCB.JPSService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.JPSService.HelloWorldResponse> HelloWorldAsync() {
            NCB.JPSService.HelloWorldRequest inValue = new NCB.JPSService.HelloWorldRequest();
            inValue.Body = new NCB.JPSService.HelloWorldRequestBody();
            return ((NCB.JPSService.JPSServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.JPSService.RegisterResponse NCB.JPSService.JPSServiceSoap.Register(NCB.JPSService.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public void Register(string id, string name, string email, string password) {
            NCB.JPSService.RegisterRequest inValue = new NCB.JPSService.RegisterRequest();
            inValue.Body = new NCB.JPSService.RegisterRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.password = password;
            NCB.JPSService.RegisterResponse retVal = ((NCB.JPSService.JPSServiceSoap)(this)).Register(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.JPSService.RegisterResponse> NCB.JPSService.JPSServiceSoap.RegisterAsync(NCB.JPSService.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.JPSService.RegisterResponse> RegisterAsync(string id, string name, string email, string password) {
            NCB.JPSService.RegisterRequest inValue = new NCB.JPSService.RegisterRequest();
            inValue.Body = new NCB.JPSService.RegisterRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((NCB.JPSService.JPSServiceSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.JPSService.LoginResponse NCB.JPSService.JPSServiceSoap.Login(NCB.JPSService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string id, string password) {
            NCB.JPSService.LoginRequest inValue = new NCB.JPSService.LoginRequest();
            inValue.Body = new NCB.JPSService.LoginRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            NCB.JPSService.LoginResponse retVal = ((NCB.JPSService.JPSServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.JPSService.LoginResponse> NCB.JPSService.JPSServiceSoap.LoginAsync(NCB.JPSService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.JPSService.LoginResponse> LoginAsync(string id, string password) {
            NCB.JPSService.LoginRequest inValue = new NCB.JPSService.LoginRequest();
            inValue.Body = new NCB.JPSService.LoginRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            return ((NCB.JPSService.JPSServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.JPSService.updateBalanceResponse NCB.JPSService.JPSServiceSoap.updateBalance(NCB.JPSService.updateBalanceRequest request) {
            return base.Channel.updateBalance(request);
        }
        
        public void updateBalance(string id, int balance) {
            NCB.JPSService.updateBalanceRequest inValue = new NCB.JPSService.updateBalanceRequest();
            inValue.Body = new NCB.JPSService.updateBalanceRequestBody();
            inValue.Body.id = id;
            inValue.Body.balance = balance;
            NCB.JPSService.updateBalanceResponse retVal = ((NCB.JPSService.JPSServiceSoap)(this)).updateBalance(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.JPSService.updateBalanceResponse> NCB.JPSService.JPSServiceSoap.updateBalanceAsync(NCB.JPSService.updateBalanceRequest request) {
            return base.Channel.updateBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.JPSService.updateBalanceResponse> updateBalanceAsync(string id, int balance) {
            NCB.JPSService.updateBalanceRequest inValue = new NCB.JPSService.updateBalanceRequest();
            inValue.Body = new NCB.JPSService.updateBalanceRequestBody();
            inValue.Body.id = id;
            inValue.Body.balance = balance;
            return ((NCB.JPSService.JPSServiceSoap)(this)).updateBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.JPSService.updateLinkedStatusResponse NCB.JPSService.JPSServiceSoap.updateLinkedStatus(NCB.JPSService.updateLinkedStatusRequest request) {
            return base.Channel.updateLinkedStatus(request);
        }
        
        public void updateLinkedStatus(string id, bool status) {
            NCB.JPSService.updateLinkedStatusRequest inValue = new NCB.JPSService.updateLinkedStatusRequest();
            inValue.Body = new NCB.JPSService.updateLinkedStatusRequestBody();
            inValue.Body.id = id;
            inValue.Body.status = status;
            NCB.JPSService.updateLinkedStatusResponse retVal = ((NCB.JPSService.JPSServiceSoap)(this)).updateLinkedStatus(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.JPSService.updateLinkedStatusResponse> NCB.JPSService.JPSServiceSoap.updateLinkedStatusAsync(NCB.JPSService.updateLinkedStatusRequest request) {
            return base.Channel.updateLinkedStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.JPSService.updateLinkedStatusResponse> updateLinkedStatusAsync(string id, bool status) {
            NCB.JPSService.updateLinkedStatusRequest inValue = new NCB.JPSService.updateLinkedStatusRequest();
            inValue.Body = new NCB.JPSService.updateLinkedStatusRequestBody();
            inValue.Body.id = id;
            inValue.Body.status = status;
            return ((NCB.JPSService.JPSServiceSoap)(this)).updateLinkedStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.JPSService.getUserResponse NCB.JPSService.JPSServiceSoap.getUser(NCB.JPSService.getUserRequest request) {
            return base.Channel.getUser(request);
        }
        
        public NCB.JPSService.User getUser() {
            NCB.JPSService.getUserRequest inValue = new NCB.JPSService.getUserRequest();
            inValue.Body = new NCB.JPSService.getUserRequestBody();
            NCB.JPSService.getUserResponse retVal = ((NCB.JPSService.JPSServiceSoap)(this)).getUser(inValue);
            return retVal.Body.getUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.JPSService.getUserResponse> NCB.JPSService.JPSServiceSoap.getUserAsync(NCB.JPSService.getUserRequest request) {
            return base.Channel.getUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.JPSService.getUserResponse> getUserAsync() {
            NCB.JPSService.getUserRequest inValue = new NCB.JPSService.getUserRequest();
            inValue.Body = new NCB.JPSService.getUserRequestBody();
            return ((NCB.JPSService.JPSServiceSoap)(this)).getUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.JPSService.GetUsernameResponse NCB.JPSService.JPSServiceSoap.GetUsername(NCB.JPSService.GetUsernameRequest request) {
            return base.Channel.GetUsername(request);
        }
        
        public string GetUsername() {
            NCB.JPSService.GetUsernameRequest inValue = new NCB.JPSService.GetUsernameRequest();
            inValue.Body = new NCB.JPSService.GetUsernameRequestBody();
            NCB.JPSService.GetUsernameResponse retVal = ((NCB.JPSService.JPSServiceSoap)(this)).GetUsername(inValue);
            return retVal.Body.GetUsernameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.JPSService.GetUsernameResponse> NCB.JPSService.JPSServiceSoap.GetUsernameAsync(NCB.JPSService.GetUsernameRequest request) {
            return base.Channel.GetUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.JPSService.GetUsernameResponse> GetUsernameAsync() {
            NCB.JPSService.GetUsernameRequest inValue = new NCB.JPSService.GetUsernameRequest();
            inValue.Body = new NCB.JPSService.GetUsernameRequestBody();
            return ((NCB.JPSService.JPSServiceSoap)(this)).GetUsernameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.JPSService.GetUserIdResponse NCB.JPSService.JPSServiceSoap.GetUserId(NCB.JPSService.GetUserIdRequest request) {
            return base.Channel.GetUserId(request);
        }
        
        public string GetUserId() {
            NCB.JPSService.GetUserIdRequest inValue = new NCB.JPSService.GetUserIdRequest();
            inValue.Body = new NCB.JPSService.GetUserIdRequestBody();
            NCB.JPSService.GetUserIdResponse retVal = ((NCB.JPSService.JPSServiceSoap)(this)).GetUserId(inValue);
            return retVal.Body.GetUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.JPSService.GetUserIdResponse> NCB.JPSService.JPSServiceSoap.GetUserIdAsync(NCB.JPSService.GetUserIdRequest request) {
            return base.Channel.GetUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.JPSService.GetUserIdResponse> GetUserIdAsync() {
            NCB.JPSService.GetUserIdRequest inValue = new NCB.JPSService.GetUserIdRequest();
            inValue.Body = new NCB.JPSService.GetUserIdRequestBody();
            return ((NCB.JPSService.JPSServiceSoap)(this)).GetUserIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.JPSService.GetUserEmailResponse NCB.JPSService.JPSServiceSoap.GetUserEmail(NCB.JPSService.GetUserEmailRequest request) {
            return base.Channel.GetUserEmail(request);
        }
        
        public string GetUserEmail() {
            NCB.JPSService.GetUserEmailRequest inValue = new NCB.JPSService.GetUserEmailRequest();
            inValue.Body = new NCB.JPSService.GetUserEmailRequestBody();
            NCB.JPSService.GetUserEmailResponse retVal = ((NCB.JPSService.JPSServiceSoap)(this)).GetUserEmail(inValue);
            return retVal.Body.GetUserEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.JPSService.GetUserEmailResponse> NCB.JPSService.JPSServiceSoap.GetUserEmailAsync(NCB.JPSService.GetUserEmailRequest request) {
            return base.Channel.GetUserEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.JPSService.GetUserEmailResponse> GetUserEmailAsync() {
            NCB.JPSService.GetUserEmailRequest inValue = new NCB.JPSService.GetUserEmailRequest();
            inValue.Body = new NCB.JPSService.GetUserEmailRequestBody();
            return ((NCB.JPSService.JPSServiceSoap)(this)).GetUserEmailAsync(inValue);
        }
        
        public int GetUserBalance() {
            return base.Channel.GetUserBalance();
        }
        
        public System.Threading.Tasks.Task<int> GetUserBalanceAsync() {
            return base.Channel.GetUserBalanceAsync();
        }
        
        public bool GetUserLinkedStatus() {
            return base.Channel.GetUserLinkedStatus();
        }
        
        public System.Threading.Tasks.Task<bool> GetUserLinkedStatusAsync() {
            return base.Channel.GetUserLinkedStatusAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.JPSService.GetUserLinkedStatusByIdResponse NCB.JPSService.JPSServiceSoap.GetUserLinkedStatusById(NCB.JPSService.GetUserLinkedStatusByIdRequest request) {
            return base.Channel.GetUserLinkedStatusById(request);
        }
        
        public bool GetUserLinkedStatusById(string id) {
            NCB.JPSService.GetUserLinkedStatusByIdRequest inValue = new NCB.JPSService.GetUserLinkedStatusByIdRequest();
            inValue.Body = new NCB.JPSService.GetUserLinkedStatusByIdRequestBody();
            inValue.Body.id = id;
            NCB.JPSService.GetUserLinkedStatusByIdResponse retVal = ((NCB.JPSService.JPSServiceSoap)(this)).GetUserLinkedStatusById(inValue);
            return retVal.Body.GetUserLinkedStatusByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.JPSService.GetUserLinkedStatusByIdResponse> NCB.JPSService.JPSServiceSoap.GetUserLinkedStatusByIdAsync(NCB.JPSService.GetUserLinkedStatusByIdRequest request) {
            return base.Channel.GetUserLinkedStatusByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.JPSService.GetUserLinkedStatusByIdResponse> GetUserLinkedStatusByIdAsync(string id) {
            NCB.JPSService.GetUserLinkedStatusByIdRequest inValue = new NCB.JPSService.GetUserLinkedStatusByIdRequest();
            inValue.Body = new NCB.JPSService.GetUserLinkedStatusByIdRequestBody();
            inValue.Body.id = id;
            return ((NCB.JPSService.JPSServiceSoap)(this)).GetUserLinkedStatusByIdAsync(inValue);
        }
    }
}
