//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCB.NWCServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private int BalanceField;
        
        private bool LinkedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Linked {
            get {
                return this.LinkedField;
            }
            set {
                if ((this.LinkedField.Equals(value) != true)) {
                    this.LinkedField = value;
                    this.RaisePropertyChanged("Linked");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NWCServices.NWCServiceSoap")]
    public interface NWCServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        NCB.NWCServices.HelloWorldResponse HelloWorld(NCB.NWCServices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.NWCServices.HelloWorldResponse> HelloWorldAsync(NCB.NWCServices.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/register", ReplyAction="*")]
        NCB.NWCServices.registerResponse register(NCB.NWCServices.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/register", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.NWCServices.registerResponse> registerAsync(NCB.NWCServices.registerRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        NCB.NWCServices.loginResponse login(NCB.NWCServices.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.NWCServices.loginResponse> loginAsync(NCB.NWCServices.loginRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateBalance", ReplyAction="*")]
        NCB.NWCServices.updateBalanceResponse updateBalance(NCB.NWCServices.updateBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.NWCServices.updateBalanceResponse> updateBalanceAsync(NCB.NWCServices.updateBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateLinkedStatus", ReplyAction="*")]
        NCB.NWCServices.updateLinkedStatusResponse updateLinkedStatus(NCB.NWCServices.updateLinkedStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateLinkedStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.NWCServices.updateLinkedStatusResponse> updateLinkedStatusAsync(NCB.NWCServices.updateLinkedStatusRequest request);
        
        // CODEGEN: Generating message contract since element name getUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUser", ReplyAction="*")]
        NCB.NWCServices.getUserResponse getUser(NCB.NWCServices.getUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUser", ReplyAction="*")]
        System.Threading.Tasks.Task<NCB.NWCServices.getUserResponse> getUserAsync(NCB.NWCServices.getUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(NCB.NWCServices.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(NCB.NWCServices.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="register", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.registerRequestBody Body;
        
        public registerRequest() {
        }
        
        public registerRequest(NCB.NWCServices.registerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public registerRequestBody() {
        }
        
        public registerRequestBody(string id, string name, string email, string password) {
            this.id = id;
            this.name = name;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.registerResponseBody Body;
        
        public registerResponse() {
        }
        
        public registerResponse(NCB.NWCServices.registerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class registerResponseBody {
        
        public registerResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(NCB.NWCServices.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string id, string password) {
            this.id = id;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(NCB.NWCServices.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class loginResponseBody {
        
        public loginResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateBalance", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.updateBalanceRequestBody Body;
        
        public updateBalanceRequest() {
        }
        
        public updateBalanceRequest(NCB.NWCServices.updateBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int balance;
        
        public updateBalanceRequestBody() {
        }
        
        public updateBalanceRequestBody(string id, int balance) {
            this.id = id;
            this.balance = balance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.updateBalanceResponseBody Body;
        
        public updateBalanceResponse() {
        }
        
        public updateBalanceResponse(NCB.NWCServices.updateBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateBalanceResponseBody {
        
        public updateBalanceResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateLinkedStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateLinkedStatus", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.updateLinkedStatusRequestBody Body;
        
        public updateLinkedStatusRequest() {
        }
        
        public updateLinkedStatusRequest(NCB.NWCServices.updateLinkedStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateLinkedStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool status;
        
        public updateLinkedStatusRequestBody() {
        }
        
        public updateLinkedStatusRequestBody(string id, bool status) {
            this.id = id;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateLinkedStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateLinkedStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.updateLinkedStatusResponseBody Body;
        
        public updateLinkedStatusResponse() {
        }
        
        public updateLinkedStatusResponse(NCB.NWCServices.updateLinkedStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateLinkedStatusResponseBody {
        
        public updateLinkedStatusResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUser", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.getUserRequestBody Body;
        
        public getUserRequest() {
        }
        
        public getUserRequest(NCB.NWCServices.getUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUserRequestBody {
        
        public getUserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public NCB.NWCServices.getUserResponseBody Body;
        
        public getUserResponse() {
        }
        
        public getUserResponse(NCB.NWCServices.getUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NCB.NWCServices.User getUserResult;
        
        public getUserResponseBody() {
        }
        
        public getUserResponseBody(NCB.NWCServices.User getUserResult) {
            this.getUserResult = getUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NWCServiceSoapChannel : NCB.NWCServices.NWCServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NWCServiceSoapClient : System.ServiceModel.ClientBase<NCB.NWCServices.NWCServiceSoap>, NCB.NWCServices.NWCServiceSoap {
        
        public NWCServiceSoapClient() {
        }
        
        public NWCServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NWCServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NWCServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NWCServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.NWCServices.HelloWorldResponse NCB.NWCServices.NWCServiceSoap.HelloWorld(NCB.NWCServices.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            NCB.NWCServices.HelloWorldRequest inValue = new NCB.NWCServices.HelloWorldRequest();
            inValue.Body = new NCB.NWCServices.HelloWorldRequestBody();
            NCB.NWCServices.HelloWorldResponse retVal = ((NCB.NWCServices.NWCServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.NWCServices.HelloWorldResponse> NCB.NWCServices.NWCServiceSoap.HelloWorldAsync(NCB.NWCServices.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.NWCServices.HelloWorldResponse> HelloWorldAsync() {
            NCB.NWCServices.HelloWorldRequest inValue = new NCB.NWCServices.HelloWorldRequest();
            inValue.Body = new NCB.NWCServices.HelloWorldRequestBody();
            return ((NCB.NWCServices.NWCServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.NWCServices.registerResponse NCB.NWCServices.NWCServiceSoap.register(NCB.NWCServices.registerRequest request) {
            return base.Channel.register(request);
        }
        
        public void register(string id, string name, string email, string password) {
            NCB.NWCServices.registerRequest inValue = new NCB.NWCServices.registerRequest();
            inValue.Body = new NCB.NWCServices.registerRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.password = password;
            NCB.NWCServices.registerResponse retVal = ((NCB.NWCServices.NWCServiceSoap)(this)).register(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.NWCServices.registerResponse> NCB.NWCServices.NWCServiceSoap.registerAsync(NCB.NWCServices.registerRequest request) {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.NWCServices.registerResponse> registerAsync(string id, string name, string email, string password) {
            NCB.NWCServices.registerRequest inValue = new NCB.NWCServices.registerRequest();
            inValue.Body = new NCB.NWCServices.registerRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((NCB.NWCServices.NWCServiceSoap)(this)).registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.NWCServices.loginResponse NCB.NWCServices.NWCServiceSoap.login(NCB.NWCServices.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public void login(string id, string password) {
            NCB.NWCServices.loginRequest inValue = new NCB.NWCServices.loginRequest();
            inValue.Body = new NCB.NWCServices.loginRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            NCB.NWCServices.loginResponse retVal = ((NCB.NWCServices.NWCServiceSoap)(this)).login(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.NWCServices.loginResponse> NCB.NWCServices.NWCServiceSoap.loginAsync(NCB.NWCServices.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.NWCServices.loginResponse> loginAsync(string id, string password) {
            NCB.NWCServices.loginRequest inValue = new NCB.NWCServices.loginRequest();
            inValue.Body = new NCB.NWCServices.loginRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            return ((NCB.NWCServices.NWCServiceSoap)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.NWCServices.updateBalanceResponse NCB.NWCServices.NWCServiceSoap.updateBalance(NCB.NWCServices.updateBalanceRequest request) {
            return base.Channel.updateBalance(request);
        }
        
        public void updateBalance(string id, int balance) {
            NCB.NWCServices.updateBalanceRequest inValue = new NCB.NWCServices.updateBalanceRequest();
            inValue.Body = new NCB.NWCServices.updateBalanceRequestBody();
            inValue.Body.id = id;
            inValue.Body.balance = balance;
            NCB.NWCServices.updateBalanceResponse retVal = ((NCB.NWCServices.NWCServiceSoap)(this)).updateBalance(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.NWCServices.updateBalanceResponse> NCB.NWCServices.NWCServiceSoap.updateBalanceAsync(NCB.NWCServices.updateBalanceRequest request) {
            return base.Channel.updateBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.NWCServices.updateBalanceResponse> updateBalanceAsync(string id, int balance) {
            NCB.NWCServices.updateBalanceRequest inValue = new NCB.NWCServices.updateBalanceRequest();
            inValue.Body = new NCB.NWCServices.updateBalanceRequestBody();
            inValue.Body.id = id;
            inValue.Body.balance = balance;
            return ((NCB.NWCServices.NWCServiceSoap)(this)).updateBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.NWCServices.updateLinkedStatusResponse NCB.NWCServices.NWCServiceSoap.updateLinkedStatus(NCB.NWCServices.updateLinkedStatusRequest request) {
            return base.Channel.updateLinkedStatus(request);
        }
        
        public void updateLinkedStatus(string id, bool status) {
            NCB.NWCServices.updateLinkedStatusRequest inValue = new NCB.NWCServices.updateLinkedStatusRequest();
            inValue.Body = new NCB.NWCServices.updateLinkedStatusRequestBody();
            inValue.Body.id = id;
            inValue.Body.status = status;
            NCB.NWCServices.updateLinkedStatusResponse retVal = ((NCB.NWCServices.NWCServiceSoap)(this)).updateLinkedStatus(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.NWCServices.updateLinkedStatusResponse> NCB.NWCServices.NWCServiceSoap.updateLinkedStatusAsync(NCB.NWCServices.updateLinkedStatusRequest request) {
            return base.Channel.updateLinkedStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.NWCServices.updateLinkedStatusResponse> updateLinkedStatusAsync(string id, bool status) {
            NCB.NWCServices.updateLinkedStatusRequest inValue = new NCB.NWCServices.updateLinkedStatusRequest();
            inValue.Body = new NCB.NWCServices.updateLinkedStatusRequestBody();
            inValue.Body.id = id;
            inValue.Body.status = status;
            return ((NCB.NWCServices.NWCServiceSoap)(this)).updateLinkedStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NCB.NWCServices.getUserResponse NCB.NWCServices.NWCServiceSoap.getUser(NCB.NWCServices.getUserRequest request) {
            return base.Channel.getUser(request);
        }
        
        public NCB.NWCServices.User getUser() {
            NCB.NWCServices.getUserRequest inValue = new NCB.NWCServices.getUserRequest();
            inValue.Body = new NCB.NWCServices.getUserRequestBody();
            NCB.NWCServices.getUserResponse retVal = ((NCB.NWCServices.NWCServiceSoap)(this)).getUser(inValue);
            return retVal.Body.getUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NCB.NWCServices.getUserResponse> NCB.NWCServices.NWCServiceSoap.getUserAsync(NCB.NWCServices.getUserRequest request) {
            return base.Channel.getUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<NCB.NWCServices.getUserResponse> getUserAsync() {
            NCB.NWCServices.getUserRequest inValue = new NCB.NWCServices.getUserRequest();
            inValue.Body = new NCB.NWCServices.getUserRequestBody();
            return ((NCB.NWCServices.NWCServiceSoap)(this)).getUserAsync(inValue);
        }
    }
}
